BusBooking/Controllers/BoardingPointsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusBooking.Models;

namespace BusBooking.Controllers
{
    public class BoardingPointsController : Controller
    {
        private BusBookingContext db = new BusBookingContext();

        // GET: BoardingPoints
        public ActionResult Index()
        {
            var boardingPoint = db.boardingPoint.Include(b => b.busDetails);
            return View(boardingPoint.ToList());
        }

        // GET: BoardingPoints/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardingPoint boardingPoint = db.boardingPoint.Find(id);
            if (boardingPoint == null)
            {
                return HttpNotFound();
            }
            return View(boardingPoint);
        }

        // GET: BoardingPoints/Create
        public ActionResult Create()
        {
            ViewBag.buisID = new SelectList(db.busDetails, "busID", "busName");
            return View();
        }

        // POST: BoardingPoints/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,buisID,pickUpPlace")] BoardingPoint boardingPoint)
        {
            if (ModelState.IsValid)
            {
                db.boardingPoint.Add(boardingPoint);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.buisID = new SelectList(db.busDetails, "busID", "busName", boardingPoint.buisID);
            return View(boardingPoint);
        }

        // GET: BoardingPoints/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardingPoint boardingPoint = db.boardingPoint.Find(id);
            if (boardingPoint == null)
            {
                return HttpNotFound();
            }
            ViewBag.buisID = new SelectList(db.busDetails, "busID", "busName", boardingPoint.buisID);
            return View(boardingPoint);
        }

        // POST: BoardingPoints/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,buisID,pickUpPlace")] BoardingPoint boardingPoint)
        {
            if (ModelState.IsValid)
            {
                db.Entry(boardingPoint).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.buisID = new SelectList(db.busDetails, "busID", "busName", boardingPoint.buisID);
            return View(boardingPoint);
        }

        // GET: BoardingPoints/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardingPoint boardingPoint = db.boardingPoint.Find(id);
            if (boardingPoint == null)
            {
                return HttpNotFound();
            }
            return View(boardingPoint);
        }

        // POST: BoardingPoints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BoardingPoint boardingPoint = db.boardingPoint.Find(id);
            db.boardingPoint.Remove(boardingPoint);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusBooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar {
            background-color: purple;
            color:black;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quick_Bus", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @if (HttpContext.Current.User.IsInRole("admin"))
    {
    <div class="container">
            @Html.Partial("admin")
    </div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Quick_Bus</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BusBooking/Views/Shared/admin.cshtml
@*<div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Quick_Bus", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("BusDetails", "Index", "BusDetails")</li>
            <li>@Html.ActionLink("Boarding Points", "Index", "BoardingPoints")</li>
        </ul>
        </div>*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background: #eee5e9;
        }
        .grid{
            margin: 80px;
            display: grid;
            grid-template-columns: repeat(3,1fr);
            grid-gap: 30px;
            align-items: center;
        }
        .grid > article{
            background: #eee5e9;
            border: none;
            box-shadow: 2px 2px 6px 0px rgba(0, 0,0,0.3);
            border-radius: 20px;
            text-align: center;
            width: 250px;
            transition: transform .3s;
        }
        .grid > article:hover{
            transform: translate(5px);
            box-shadow: 2px 2px 26px 0px rgba(0, 0,0,0.3);
        }
        .grid >article img{
            width: 100%;
            border-top-left-radius: 20px;
            border-top-right-radius: 20px;
        }
        .text
        {
            padding: 0 20px 20px;
        }
        .text h3{
            text-transform: uppercase;
        }
        .text button{
            background: #ef6f6c;
            border-radius: 20px;
            border: none;
            color: #fff;
            padding: 10px;
            width: 100%;
            text-transform: uppercase;
            cursor: pointer;
        }
        @*@media(max-width:768px){
            .grid{
                grid-template-columns: repeat(2,1fr);
            }
        }
        @media(max-width:768px){
            .grid{
                     {

                 
                grid-template-columns: repeat(1,1fr);
            }
                     }
            .grid > article{
                {
                text-align: center;
            }
                }
        }*@
    </style>
</head>
<body>
    <div class="container">
        <main class="grid">
            <article>
                <form action="~/BusDetails/Create" method="post" class="form">
                    <img src="~/images/add bus.png"  width="100" height="100"/>
                    <div class="text">
                        <button>
                            ADD BUS
                        </button>
                    </div>
                </form>
            </article>

            <article>
                <form action="~/Bookings/Index" method="post" class="form">
                    <img src="~/images/booking details.png" width="100" height="100" />
                    <div class="text">
                        <button>
                            BOOKING DETAILS
                        </button>
                    </div>
                </form>
            </article>

            <article>
                <form action="~/BoardingPoints/Index" method="post" class="form">
                    <img src="~/images/route details.png" width="100" height="100"/>
                    <div class="text">
                        <button>
                            BOARDING DETAILS
                        </button>
                    </div>
                </form>
            </article>           
        </main>
    </div>
</body>
</html>